### ISSUE TITLE
Supported or to archive?

### ISSUE THREAD

**Issue by esolitos** [nymedia/dropbox-sdk-php#2]
This is still in use, supported or we can archive?

**Comment by eiriksm** [comment]
I have no idea :o

**Comment by eiriksm** [comment]
...seems to be in use still. And it's public FYI

**Comment by esolitos** [comment]
Good point, do you think that given it's public we should perhaps indicate in composer.json that it is abandoned/non-maintained?

**Comment by eiriksm** [comment]
Sure, let's do that

**Comment by esolitos** [comment]
🤦🏼 I commit the change, but referred to #1 insteaf od #2. 😅 
Anyway it's done, maker.
